// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqjs8INEh8kulKPmGIOdXi-pcNdnh14IY',
    appId: '1:330519490780:android:7c804a29dc880ca1fd0419',
    messagingSenderId: '330519490780',
    projectId: 'learn-kyrgyz-2df55',
    storageBucket: 'learn-kyrgyz-2df55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6PDBPPHYJf-JtDZT1zPBtrpuhewErfhI',
    appId: '1:330519490780:ios:cbaa9cb276a71a0cfd0419',
    messagingSenderId: '330519490780',
    projectId: 'learn-kyrgyz-2df55',
    storageBucket: 'learn-kyrgyz-2df55.firebasestorage.app',
    iosBundleId: 'com.example.learnKyrgyz',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUPs9Vx9cxQhk7GpvsOT9LooRBFssMpb4',
    appId: '1:330519490780:web:ba5c64a3dba8732ffd0419',
    messagingSenderId: '330519490780',
    projectId: 'learn-kyrgyz-2df55',
    authDomain: 'learn-kyrgyz-2df55.firebaseapp.com',
    storageBucket: 'learn-kyrgyz-2df55.firebasestorage.app',
    measurementId: 'G-W477WFJWH0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6PDBPPHYJf-JtDZT1zPBtrpuhewErfhI',
    appId: '1:330519490780:ios:cbaa9cb276a71a0cfd0419',
    messagingSenderId: '330519490780',
    projectId: 'learn-kyrgyz-2df55',
    storageBucket: 'learn-kyrgyz-2df55.firebasestorage.app',
    iosBundleId: 'com.example.learnKyrgyz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUPs9Vx9cxQhk7GpvsOT9LooRBFssMpb4',
    appId: '1:330519490780:web:1236f0ad092ee921fd0419',
    messagingSenderId: '330519490780',
    projectId: 'learn-kyrgyz-2df55',
    authDomain: 'learn-kyrgyz-2df55.firebaseapp.com',
    storageBucket: 'learn-kyrgyz-2df55.firebasestorage.app',
    measurementId: 'G-XT86RL3NZB',
  );
}
